services:
  postiz:
    # image: ghcr.io/gitroomhq/postiz-app:latest
    image: registry.paynepride.com/gitroomhq/postiz-app:nostr-test2
    container_name: postiz
    restart: always
    env_file: .env
    environment:
      # You must change these. Replace `postiz.your-server.com` with your DNS name - what your web browser sees.
      MAIN_URL: "https://postiz.paynepride.com"
      FRONTEND_URL: "https://postiz.paynepride.com"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.paynepride.com/api"
      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: "postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true" # Required for self-hosting.
      # The container images are pre-configured to use /uploads for file storage.
      # You probably should not change this unless you have a really good reason!
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - /tank/encrypted/docker/postiz/config:/config/
      - /tank/encrypted/docker/postiz/uploads:/uploads/
    ports:
      - 5002:5000
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    labels:
      traefik.enable: "true"
      traefik.http.routers.postiz.rule: Host(`postiz.paynepride.com`)
      traefik.http.routers.postiz.tls.certresolver: letsencrypt
      traefik.http.routers.postiz.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.postiz.tls.domains[0].sans: "*.paynepride.com"
      # traefik.http.routers.postiz.middlewares: default-whitelist@file
      traefik.http.services.postiz.loadbalancer.server.port: 5000
 
  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - /tank/encrypted/docker/postiz/postgres:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - /tank/encrypted/docker/postiz/redis-data:/data
    networks:
      - postiz-network
 
networks:
  postiz-network:
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.71.0.0/16
