services:
  # caddy:
  #   container_name: caddy
  #   image: docker.io/library/caddy:2-alpine
  #   network_mode: host
  #   restart: unless-stopped
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy-data:/data:rw
  #     - caddy-config:/config:rw
  #   environment:
  #     - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost}
  #     - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1m"
  #       max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - phantomlink
    volumes:
      - /tank/encrypted/docker/the-pit-zfs/searxng/redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - phantomlink
    ports:
      - "8070:8080"
    volumes:
      - /tank/encrypted/docker/the-pit-zfs/searxng/searxng:/etc/searxng:rw
    env_file: .env
    environment:
      # - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      traefik.enable: "true"
      traefik.http.routers.searxng.rule: Host(`searxng.paynepride.com`)
      traefik.http.routers.searxng.tls.certresolver: letsencrypt
      traefik.http.routers.searxng.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.searxng.tls.domains[0].sans: "*.paynepride.com"
      traefik.http.routers.searxng.middlewares: default-whitelist@file
      traefik.http.services.searxng.loadbalancer.server.port: 8080

networks:
  phantomlink:
    external: true 
